name: LeetCode Stats

on:
  push:
    paths:
      - './leetcode/**'
  pull_request:
    paths:
      - './leetcode/**'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: true
        default: 'Updating leetcode stats'

jobs:
  analyze-and-update-stats:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
      
    - name: Ensure README.md is writable
      run: chmod +rw ./leetcode/README.md

    - name: Ensure data.json is writable
      run: chmod +rw ./docs/data.json

    - name: Analyze LeetCode Solutions
      run: python .github/scripts/analyze_leetcode.py

    - name: Commit and Push Changes (if any)
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "auto-commit-update-leetcode-stats"
